name: Test Case
description: Create a new test case
title: "[Test Case] <Title>"
labels: [test-case]
body:
  - type: input
    id: id
    attributes:
      label: Test Case ID
  - type: input
    id: module
    attributes:
      label: Module
  - type: textarea
    id: steps
    attributes:
      label: Steps to Execute
  - type: input
    id: expected
    attributes:
      label: Expected Result
``
