name: Test Case
description: Create a new test case
title: "Title of test case"
labels: [test-case],[test-case: not executed],[test-case: priority-1]
body:
  - type: textarea
    id: precondition
    attributes:
      label: Pre-Condition
      placeholder: Mention Pre-Condition steps needed to execute this case
  - type: textarea
    id: steps
    attributes:
      label: Steps to Execute
      placeholder: Describe the steps clearly
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      placeholder: What should happen?
